// Tipos e interfaces para el registro de usuarios y tiendas

export interface PasswordStrength {
  score: number
  label: string
}

export type SlugStatus = 'idle' | 'checking' | 'available' | 'taken' | 'invalid'
export type EmailStatus = 'idle' | 'checking' | 'available' | 'taken' | 'invalid'

export interface RegisterFormData {
  email: string
  password: string
  businessName: string
  tenantSlug: string
  plan: 'esencial' | 'pro'
}

export interface FormValidationState {
  emailError: string
  emailTouched: boolean
  businessNameTouched: boolean
  passwordTouched: boolean
  termsTouched: boolean
}

export interface SlugGenerationState {
  slugStatus: SlugStatus
  generatingSlug: boolean
  slugSuggestions: string[]
  showSlugSuggestions: boolean
  loadingSuggestions: boolean
  slugAutoGenerated: boolean
  slugManuallyCleared: boolean
}

export interface RegisterPageProps {
  onComplete?: () => void
}
